### PR TITLE
no fat arrows

### PR DESCRIPTION
**Pull request by dyoder**

### CODE REVIEW

**Comment by ms-ati** [comment]
Out of curiosity, why prefer `self = @` to fat arrows?

**Comment by automatthew** [comment]
Ah, that was an experiment on dyoder's part to see if it would be faster.

It wasn't, but we never told Giles that, I don't think.  I may revert that merge.

**Comment by ms-ati** [comment]
Bah, glad I asked then :tomato:

**Comment by automatthew** [comment]
@gilesbowkett ^

my bad for not nuking that branch earlier.

**Comment by automatthew** [comment]
Reverted:

https://github.com/pandastrike/jsck/commit/1c47c4a3579db2bf3882120f45e05702418ec148

**Comment by gilesbowkett** [comment]
doh

**Pull request merged**
